name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Tests (optional)
      run: echo "No tests yet"

    - name: Build Docker Image
      run: docker build -t flask-app .

    - name: Deploy
      run: echo "Manual deployment step or webhook here"
